Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('58', 'Tennyson', 'Detroit', 'Michigan', '48267');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('860', 'Cambridge', 'Galveston', 'Texas', '77554');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('211', 'Del Sol', 'Iowa City', 'Iowa', '52245');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('17', 'Reindahl', 'New Haven', 'Connecticut', '06533');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('9', 'Florence', 'Philadelphia', 'Pennsylvania', '19151');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('456', 'Bartelt', 'Milwaukee', 'Wisconsin', '53277');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('39', 'Forest Run', 'Little Rock', 'Arkansas', '72215');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('6', 'Sage', 'Amarillo', 'Texas', '79159');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('9', 'Westridge', 'Waterbury', 'Connecticut', '06721');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('74', 'Fordem', 'Ogden', 'Utah', '84403');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('86', 'Walton', 'Ogden', 'Utah', '84403');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('69', 'Riverside', 'Baton Rouge', 'Louisiana', '70883');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('829', 'Cody', 'Vienna', 'Virginia', '22184');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('597', 'Thackeray', 'New York City', 'New York', '10280');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('875', 'Morrow', 'Chicago', 'Illinois', '60691');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('5265', 'Marquette', 'Concord', 'California', '94522');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('302', 'Forster', 'San Antonio', 'Texas', '78210');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('5', 'Paget', 'Rochester', 'New York', '14609');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('92', 'Bluestem', 'Dallas', 'Texas', '75226');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('152', 'Cascade', 'Terre Haute', 'Indiana', '47812');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('418', 'School', 'Fort Wayne', 'Indiana', '46805');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('843', 'Weeping Birch', 'Vienna', 'Virginia', '22184');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('73', 'Veith', 'Charlotte', 'North Carolina', '28230');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('55', 'Northfield', 'Bethesda', 'Maryland', '20892');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('35', 'Ryan', 'Raleigh', 'North Carolina', '27626');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('28', 'Waxwing', 'Topeka', 'Kansas', '66667');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('8', 'Mandrake', 'Fort Lauderdale', 'Florida', '33315');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('729', 'Warbler', 'Charlotte', 'North Carolina', '28289');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('621', 'Sullivan', 'Pensacola', 'Florida', '32595');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('96', 'Pierstorff', 'Long Beach', 'California', '90840');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('51', 'Jay', 'Little Rock', 'Arkansas', '72231');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('871', 'Gerald', 'Boston', 'Massachusetts', '02208');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('773', 'Del Mar', 'Washington', 'District of Columbia', '20580');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('445', 'Lerdahl', 'San Jose', 'California', '95113');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('30', 'Bunting', 'Miami', 'Florida', '33147');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('196', 'Vera', 'Miami Beach', 'Florida', '33141');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('74', 'Miller', 'San Diego', 'California', '92176');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('542', 'Larry', 'Pompano Beach', 'Florida', '33064');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('2', 'Elgar', 'Aurora', 'Colorado', '80045');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('232', 'Schiller', 'Winston Salem', 'North Carolina', '27110');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('407', 'Union', 'Fresno', 'California', '93786');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('247', 'Independence', 'Indianapolis', 'Indiana', '46278');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('45', 'Brentwood', 'Colorado Springs', 'Colorado', '80951');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('24', 'Hovde', 'Palmdale', 'California', '93591');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('70', 'Garrison', 'Maple Plain', 'Minnesota', '55579');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('60', 'Chinook', 'New York City', 'New York', '10024');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('17803', 'Green Ridge', 'Columbus', 'Ohio', '43210');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('44', 'Lillian', 'Charleston', 'West Virginia', '25356');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('85664', 'Ramsey', 'El Paso', 'Texas', '79994');
Insert Into CustomerAddress (StreetNumber, StreetName, City, AddressState, Zipcode) values ('131', 'Fair Oaks', 'Lexington', 'Kentucky', '40581');
